# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CallingWithChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CallingWithChat
  pod 'AzureCommunicationUICalling', '1.12.0-beta.1'
  pod 'AzureCommunicationUIChat', '1.0.0-beta.4'
end
